[build]
builder = "nixpacks"

[deploy]
startCommand = "bash -lc \"python scheduler_refresh.py --once || true; python main.py\""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
