[build]
builder = "nixpacks"

[deploy]
startCommand = "bash -lc \"python -u scheduler_refresh.py --once || true & exec python -u main.py\""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
